import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Poppins, Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/shared/theme-provider";
import NavbarWrapper from "@/components/shared/Nav/NavbarWrapper";

export const metadata: Metadata = {
  title: "Orient-Express",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  fallback: ["system-ui", "arial"],
});
const geist = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        {/* <NavbarWrapper /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
