services:

  postgres:
    image: postgres:16.4
    container_name: dev-postgres
    restart: always
    environment:
      POSTGRES_DB: orient-express
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: red123
    volumes: 
      - "./data/database:/var/lib/postgresql/data"
    ports:
      - "5432:5432"